#!/usr/bin/env ruby

require 'optparse'

require "./src/util/util.rb"
require "./src/util/rolling_aggregate.rb"
require "./src/upload_stats.rb"
require "./src/logfile_pusher.rb"
require "./src/eventql_uploader.rb"
require "./src/sqlite_uploader.rb"

# parse arguments
options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: logpusher.rb [options]"

  opts.on("-f", "--file filename", "Set the logfile to import") do |f|
    options[:file] = f
  end

  opts.on("-r", "--regex regex", "The Regex of the logline") do |r|
    options[:regex] = r
  end

  opts.on("-u", "--uploader uploader", "Set the db engine to use") do |u|
    options[:uploader] = u
  end

  opts.on("-t", "--table table", "Set the table name") do |t|
    options[:table] = t
  end

  opts.on("-h", "--host hostname", "Set the hostname") do |h|
    options[:host] = h
  end

  opts.on("-p", "--port port", "Set the port") do |p|
    options[:port] = p
  end

  opts.on("-u", "--user username", "Set the username") do |u|
    options[:user] = u
  end

  opts.on(nil, "--password password", "Set the password") do |u|
    options[:user] = u
  end

  opts.on("-d", "--database db", "Set the database") do |d|
    options[:database] = d
  end

  opts.on(nil, "--auth_token token", "Set the auth token") do |a|
    options[:auth_token] = a
  end

  opts.on("-q", "--quiet", "Run quietly") do |q|
    options[:quiet] = q
  end

  opts.on("-?", "--help", "help") do
    $stderr.puts opts
    exit
  end
end.parse!

mandatory_args = [:file, :regex, :uploader, :table, :host, :port, :database]
missing = mandatory_args.select{ |param| options[param].nil? }
unless missing.empty?
  puts "missing arguments: #{missing.join(', ')}. Run logpusher.rb --help for help"
  exit
end

auth_data = {};
if options[:user]
  auth_data[:user] = options[:user]
end

if options[:password]
  auth_data[:password] = options[:password]
end

if options[:auth_token]
  auth_data[:auth_token] = options[:auth_token]
end

logfile_pusher = nil
begin
  uploader = nil
  case options[:uploader]
  when "eventql"
    uploader = EventQLUploader.new(
        options[:table],
        options[:host],
        options[:port],
        options[:database],
        auth_data)
  when "sqlite"
    uploader = SQLiteUploader.new(
        options[:table],
        options[:database])
  else
    puts "unknown uploader #{options[:uploader]}"
    exit
  end

  logfile_pusher = LogfilePusher.new(
      options[:file],
      options[:regex],
      uploader,
      options[:quiet].nil? ? false : true)
  logfile_pusher.run

rescue SystemExit, Interrupt
  if logfile_pusher
    logfile_pusher.stop
  end
  exit(0)

rescue

  if logfile_pusher
    logfile_pusher.stop
  end
  $stderr.puts "ERROR: #{$!} \n"
  exit(1)
end

